### ISSUE TITLE
버그리포트

### ISSUE THREAD

**Issue by JunseoHo** [JunseoHo/minishell#10]
- echo yaong -n
- 인자 없는 cd
- utill
- HOME 환경변수 unset 후 'cd ~'하면 세그멘테이션 폴트
-  자잘한 Leaks

**Comment by gotjd7837** [comment]
해결

**Comment by gotjd7837** [comment]
- clear 명령어 실행 시 "TERM environment variable not set." 에러 발생
- bash에서 실행 시 환경변수 TERM을 지웠을 경우 같은 에러가 발생하는데, minishell애서는 TERM 환경변수가 존재하는데도 불구하고 위와 같은 에러 발생
