### ISSUE TITLE
해성이형, 이거 해'줘'

### ISSUE THREAD

**Issue by JunseoHo** [JunseoHo/minishell#5]
msh_expand_input 폴더의 함수에 대하여...

1.  norm 맞추기
2. 에러 보고

**Comment by gotjd7837** [comment]
1. norm 맞추기 ✅

2. 에러보고
- $PATH와 같이 선언되어 있는 환경변수를 한번 이상 입력하면 에러 발생
-> 에러 코드 : "pointer being freed was not allocated" 
-> 할당 되지 않은 메모리에서 메모리를 해제하려고 시도하고 있을 때 발생하는 에러

**Comment by gotjd7837** [comment]
해결
